#!/bin/bash -x
INSTANCE_ID=$(
    aws ec2 describe-instances \
        --output json \
        --filter Name=instance-state-name,Values=running |
    python \
        -c 'import json; import sys; print json.load(sys.stdin)["Reservations"][0]["Instances"][0]["InstanceId"]'
)

aws ec2 terminate-instances --instance-ids $INSTANCE_ID
